' 1°'
' Aqui comeca o inicio do arqvio - Tem que colocar esse link para ele conseguir usar o C4-model em diagrama'
@startuml Teste
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System("System", "System", "System desc")
@enduml
